### ISSUE TITLE
Listing bucket credentials only shows the first 20

### ISSUE THREAD

**Issue by fernando-villalba** [civo/cli#451] opened 2024-08-22 12:53 UTC
## Description

When listing bucket credentials, only the first 20 items are shown.

### Reproducing the issue

1. Create 25 credentials

```sh
for z in test-{1..25} ; do civo bucket credential create $z ; done
```

2. List them the number of credentials:

```sh
civo bucket credential ls -o custom -f name | wc -l 
```

Output is 20

3. Clean up

And the following to clean up the credentials created after checking:

```sh
for z in test-{1..25} ; do civo bucket credential delete $z -y ; done
```

## Acceptance criteria

* Ensure that all credentials are listed.
* Ensure that no other listing of resources has this issue and create tickets as necessary

**Comment by Pushkarmondal** [comment] 2024-09-01 04:52
Hey @fernando-villalba I think that the default size of listing is 20. In civo docs they mention that default size is 20

**Comment by Praveen005** [comment] 2024-09-04 15:27
Hi @uzaxirr,

I worked on this issue and would like to explain my approach for your review.

The issue here is occurring because, [ListObjectStoreCredentials](https://github.com/civo/civogo/blob/4fee779533b0cfd41ff2f53b4ea57b052848ac05/objectstore_credential.go#L46-L59) method gives us only the first page of the response and `perPage` default value is 20.



To get the complete response, we need to change the request url to something like,
`url := fmt.Sprintf("/v2/objectstore/credentials?page=%d", page)`


**These parameters can be sent along with the request, see the API doc [here](https://www.civo.com/api/object-stores#:~:text=objectstore/credentials.-,Request,-The%20following%20parameters)**

-----------------------------------------------------------------------------
We can change the `ListObjectStoreCredentials()` method to `ListObjectStoreCredentials(page int)`

And then query all the pages.

-------------------------------------------------------------------------------------
I tested the approach and it works as intended:

<img width="526" alt="Screenshot 2024-09-04 204449" src="https://github.com/user-attachments/assets/a692bb71-0c32-45fa-b7bd-a7fb9b07197c">

Result:

<img width="720" alt="Screenshot 2024-09-04 202909" src="https://github.com/user-attachments/assets/2a2e97a3-f3dc-4080-b3f5-6fff49db5f4d">

------------------------------------------------------------------------

Question:

Should I open an issue in `civogo` requesting these changes?

Thank You!

**Comment by Pushkarmondal** [comment] 2024-09-04 15:31
I think it would be better to not restrict only 30.

**Comment by Praveen005** [comment] 2024-09-04 15:38
> I think it would be better to not restrict only 30.

Hi @Pushkarmondal,

keeping the current default to 20 is okay I feel. I have used 30, just to test my approach.

**Comment by Pushkarmondal** [comment] 2024-09-04 15:40
Ok, i already created a pull request for that in Civogo

**Comment by uzaxirr** [comment] 2024-09-05 04:16
hii @Praveen005 
your approach looks fine. please create a PR

**Comment by Pushkarmondal** [comment] 2024-09-05 04:30
Hey @uzaxirr I have created a issue some times ago on this issue in `Civogo`, please check once

**Comment by uzaxirr** [comment] 2024-09-23 20:44
@Praveen005 i have merged the civogo PR and made a new release: https://github.com/civo/civogo/releases/tag/v0.3.79
Please raise a PR for this issue

**Closed as completed** 2024-09-24 18:55 UTC
